-- UNION 이용, 세로로 두 테이블 붙이기
-- UNION 절 앞 뒤의 쿼리문 결과의 열 수가 반드시 같아야 함!!


(   SELECT DATE_FORMAT(A.SALES_DATE,"%Y-%m-%d") AS SALES_DATE,
        A.PRODUCT_ID, A.USER_ID, A.SALES_AMOUNT
    FROM ONLINE_SALE AS A
    WHERE SALES_DATE LIKE "2022-03%"
)
UNION
(   SELECT DATE_FORMAT(B.SALES_DATE,"%Y-%m-%d") AS SALES_DATE,
        B.PRODUCT_ID, NULL AS USER_ID, B.SALES_AMOUNT
    FROM OFFLINE_SALE AS B
    WHERE SALES_DATE LIKE "2022-03%"
)

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
