-- 코드를 입력하세요
SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, A.GENDER, COUNT(DISTINCT A.USER_ID) AS USERS
    #Group 내에서 중복되는 User ID 제거
        # SELECT문이 GROUP문보다 다음에 실행된다!!
FROM USER_INFO AS A

JOIN ONLINE_SALE AS B
ON A.USER_ID = B.USER_ID

WHERE !ISNULL(A.GENDER)

GROUP BY YEAR,MONTH,GENDER

ORDER BY YEAR,MONTH,GENDER