-- 코드를 입력하세요
SELECT MONTH(A.START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A

WHERE DATEDIFF(A.START_DATE,"2022-08-01") >= 0
    AND DATEDIFF(A.START_DATE,"2022-11-01") < 0
    AND (
        SELECT COUNT(*)
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
        WHERE B.CAR_ID = A.CAR_ID
            AND DATEDIFF(B.START_DATE,"2022-08-01") >= 0
            AND DATEDIFF(B.START_DATE,"2022-11-01") < 0
        ) >= 5

GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0

ORDER BY MONTH, CAR_ID DESC