-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS A

WHERE A.PRICE = (
    SELECT MAX(B.PRICE) 
    FROM FOOD_PRODUCT AS B
    WHERE B.CATEGORY = A.CATEGORY
)
    AND
    CATEGORY in ('과자', '국', '김치', '식용유')
    

ORDER BY MAX_PRICE DESC