-- 코드를 입력하세요
SELECT A.CAR_ID, IF(SUM(A.AV)>0,"대여중","대여 가능") AS AVAILABILITY
FROM (
    SELECT CAR_ID,
        IF(DATEDIFF(START_DATE,"2022-10-16")<=0 AND DATEDIFF(END_DATE,"2022-10-16")>=0 , "1","0") AS AV
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS A

GROUP BY A.CAR_ID

ORDER BY CAR_ID DESC