-- 코드를 입력하세요
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE*C.SALES) AS TOTAL_SALES

FROM BOOK AS A

LEFT JOIN AUTHOR AS B
ON A.AUTHOR_ID = B.AUTHOR_ID

RIGHT JOIN BOOK_SALES AS C
ON A.BOOK_ID = C.BOOK_ID

WHERE DATE_FORMAT(C.SALES_DATE,"%Y-%m-%d") LIKE "2022-01%"

GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY

ORDER BY AUTHOR_ID, CATEGORY DESC