-- 코드를 입력하세요
SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK AS A

RIGHT JOIN BOOK_SALES AS B
ON B.BOOK_ID = A.BOOK_ID

WHERE DATE_FORMAT(B.SALES_DATE,"%Y-%m-%d") LIKE "2022-01%"

GROUP BY A.CATEGORY

ORDER BY CATEGORY