-- From 절 Sub 쿼리 이용, 중복 제거

SELECT DISTINCT C.CAR_ID FROM
(
SELECT B.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS A

RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
ON A.CAR_ID = B.CAR_ID

WHERE A.CAR_TYPE = "세단"
    AND DATEDIFF(B.START_DATE,"2022-10-01") >= 0
    AND DATEDIFF(B.START_DATE,"2022-11-01") < 0
) C

ORDER BY CAR_ID DESC