-- 코드를 입력하세요
SELECT B.HISTORY_ID,
    IF(ISNULL(C.DISCOUNT_RATE),
       B.DURATION*A.DAILY_FEE,
       TRUNCATE(B.DURATION*A.DAILY_FEE*(100-C.DISCOUNT_RATE)/100,0) ) AS FEE
    /*,B.DURATION, B.DURATION_TYPE, C.DISCOUNT_RATE*/

FROM (
    SELECT CAR_ID, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = "트럭"
    ) AS A

JOIN (
    SELECT HISTORY_ID, CAR_ID,
        DATEDIFF(END_DATE,START_DATE)+1 AS DURATION,
        IF(DATEDIFF(END_DATE,START_DATE)+1>=90,"90일 이상",
           IF(DATEDIFF(END_DATE,START_DATE)+1>=30,"30일 이상",
              IF(DATEDIFF(END_DATE,START_DATE)+1>=7,"7일 이상", NULL ) ) ) AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    ) AS B
ON A.CAR_ID = B.CAR_ID

LEFT JOIN (
    SELECT DISCOUNT_RATE, DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = "트럭"
    ) AS C
ON B.DURATION_TYPE = C.DURATION_TYPE

ORDER BY FEE DESC, HISTORY_ID DESC
