-- TRUNCATE: 버림, ROUND: 반올림
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE,START_DATE))+1,1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE AVERAGE_DURATION >= 7 -- Where문이 Group보다 선적용이므로, 안됨!
GROUP BY CAR_ID
HAVING AVG(DATEDIFF(END_DATE,START_DATE))+1 >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

-- DATE_DIFF: 날짜 빼기에 최고!