-- 코드를 입력하세요
SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A

LEFT JOIN PATIENT AS B
ON A.PT_NO = B.PT_NO

LEFT JOIN DOCTOR AS C
ON A.MDDR_ID = C.DR_ID

WHERE A.MCDP_CD = "CS"
    AND DATEDIFF(A.APNT_YMD,"2022-04-13")=0
    AND (A.APNT_CNCL_YN = "N" OR DATEDIFF(A.APNT_CNCL_YMD,"2022-04-13")>=0)

ORDER BY A.APNT_YMD