-- 코드를 입력하세요
SELECT A.MEMBER_NAME, B.REVIEW_TEXT,
    DATE_FORMAT(B.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
    -- ,C.REVIEW_COUNT

FROM MEMBER_PROFILE AS A

JOIN REST_REVIEW AS B
ON A.MEMBER_ID = B.MEMBER_ID

JOIN (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
) AS C
ON A.MEMBER_ID = C.MEMBER_ID


WHERE C.REVIEW_COUNT = (
    SELECT MAX(D.REVIEW_COUNT)
    FROM (
        SELECT COUNT(*) AS REVIEW_COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ) AS D
)
ORDER BY REVIEW_DATE, REVIEW_TEXT