-- 코드를 입력하세요
SET @TOTAL_USER = (
    SELECT COUNT(*)
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021);

SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH,
    COUNT(*) AS PUCHASED_USERS, 
    ROUND(COUNT(*)/@TOTAL_USER,1) AS PUCHASED_RATIO

FROM (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) AS A

JOIN (
    SELECT USER_ID, COUNT(*) AS NUM_USERS, SALES_DATE
    FROM ONLINE_SALE
    GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE), USER_ID
)AS B
ON A.USER_ID = B.USER_ID

GROUP BY YEAR, MONTH

ORDER BY YEAR, MONTH