-- 코드를 입력하세요
SELECT A.NAME,A.DATETIME
FROM ANIMAL_INS AS A
LEFT JOIN ANIMAL_OUTS AS B -- LEFT JOIN으로 하면, A는 모두, B는 A에 있는 값만 합쳐진다! -> A엔 있고 B엔 없으면 NULL로 받아와짐
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE ISNULL(B.DATETIME)
ORDER BY A.DATETIME
LIMIT 3 -- 상위 3개만 출력