-- 코드를 입력하세요
SELECT D.CART_ID
FROM (
    SELECT A.CART_ID
    FROM CART_PRODUCTS AS A
    GROUP BY CART_ID
    ) AS D

JOIN (
    SELECT CART_ID, COUNT(*) AS COUNTMILK
    FROM CART_PRODUCTS
    WHERE NAME = "Milk"
    GROUP BY CART_ID
) AS B
ON D.CART_ID = B.CART_ID

JOIN (
    SELECT CART_ID, COUNT(*) AS COUNTYOGURT
    FROM CART_PRODUCTS
    WHERE NAME = "Yogurt"
    GROUP BY CART_ID
) AS C
ON D.CART_ID = C.CART_ID

ORDER BY CART_ID