-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS FHTOTAL
    FROM FIRST_HALF
    GROUP BY FLAVOR
) AS A

JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULYTOTAL
    FROM JULY
    GROUP BY FLAVOR
) AS B
ON A.FLAVOR = B.FLAVOR

ORDER BY A.FHTOTAL + B.JULYTOTAL DESC

LIMIT 3