-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE,
    TRUNCATE( A.DAILY_FEE*30*(100-B.DISCOUNT_RATE)/100, 0) AS FEE

FROM (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE in ("SUV", "세단")
    ) AS A

LEFT JOIN (
    SELECT DISCOUNT_RATE, CAR_TYPE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = "30일 이상"
) AS B
ON A.CAR_TYPE = B.CAR_TYPE

LEFT JOIN (
    SELECT COUNT(*) AS FAILCOUNT, CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE !(( DATEDIFF(END_DATE,"2022-11-01")<0 )
        OR ( DATEDIFF(START_DATE,"2022-12-01")>=0 ))
    GROUP BY CAR_ID
) AS C
ON A.CAR_ID = C.CAR_ID

WHERE ISNULL(C.FAILCOUNT)
    AND A.DAILY_FEE*30*(100-B.DISCOUNT_RATE)/100>=500000
    AND A.DAILY_FEE*30*(100-B.DISCOUNT_RATE)/100<2000000

ORDER BY FEE DESC,CAR_TYPE,CAR_ID